const DB_KEY='mymoney-v1';
const defaultData={
  entries:[],
  accounts:[{id:'cash',name:'現金',type:'現金'},{id:'bank',name:'主要銀行',type:'銀行'},{id:'card',name:'信用卡',type:'信用卡'}],
  categories:{expense:['餐飲','交通','購物','娛樂','居家','電信／訂閱','教育','醫療','旅遊','禮物','投資','其他'],income:['薪資','獎金','投資收益','退款','其他收入'],transfer:['轉帳']},
  budget:0
};
let data=loadData();
let entryType='expense';
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
function loadData(){try{return {...structuredClone(defaultData),...JSON.parse(localStorage.getItem(DB_KEY)||'{}')}}catch{return structuredClone(defaultData)}}
function saveData(){localStorage.setItem(DB_KEY,JSON.stringify(data));renderAll()}
function money(n){return new Intl.NumberFormat('zh-TW',{style:'currency',currency:'TWD',maximumFractionDigits:0}).format(Number(n)||0)}
function monthKey(d=new Date()){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}
function todayKey(){return new Date().toISOString().slice(0,10)}
function currentMonthEntries(){const mk=monthKey();return data.entries.filter(e=>e.date.startsWith(mk))}
function calcMonth(){const es=currentMonthEntries();let income=0,expense=0;es.forEach(e=>{if(e.type==='income')income+=e.amount;if(e.type==='expense')expense+=e.amount});return{income,expense,balance:income-expense}}
function nav(view){$$('.view').forEach(v=>v.classList.remove('active'));$(`#${view}View`).classList.add('active');$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.nav===view));if(view==='records')renderRecords();if(view==='analytics')renderAnalytics();if(view==='accounts')renderAccounts()}
function iconFor(cat){const map={'餐飲':'🍱','交通':'🚌','購物':'🛍️','娛樂':'🎮','居家':'🏠','電信／訂閱':'📱','教育':'📚','醫療':'🏥','旅遊':'✈️','禮物':'🎁','投資':'📈','其他':'📦','薪資':'💼','獎金':'🎉','投資收益':'💹','退款':'↩️','其他收入':'💰','轉帳':'↔️'};return map[cat]||'•'}
function txHTML(e){const sign=e.type==='income'?'+':e.type==='expense'?'-':'';const cls=e.type==='income'?'positive':e.type==='expense'?'negative':'';return `<div class="tx-item"><div class="tx-icon">${iconFor(e.category)}</div><div class="tx-main"><div class="tx-title">${escapeHtml(e.note||e.category)}</div><div class="tx-sub">${e.category} · ${accountName(e.accountId)} · ${e.date} ${e.time||''}</div></div><div class="tx-amt ${cls}">${sign}${money(e.amount)}</div></div>`}
function escapeHtml(s=''){return s.replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]))}
function accountName(id){return data.accounts.find(a=>a.id===id)?.name||'未指定'}
function renderHome(){const now=new Date();$('#monthLabel').textContent=`${now.getFullYear()} 年 ${now.getMonth()+1} 月`;const m=calcMonth();$('#balanceAmount').textContent=money(m.balance);$('#incomeAmount').textContent=money(m.income);$('#expenseAmount').textContent=money(m.expense);const budget=data.budget||0;$('#budgetText').textContent=budget?`${money(m.expense)} / ${money(budget)}`:'尚未設定';$('#budgetProgress').style.width=budget?`${Math.min(100,m.expense/budget*100)}%`:'0%';const today=data.entries.filter(e=>e.date===todayKey()).sort(sortEntries);$('#todayTotal').textContent=money(today.filter(e=>e.type==='expense').reduce((s,e)=>s+e.amount,0));$('#todayList').innerHTML=today.length?today.slice(0,4).map(txHTML).join(''):'<div class="empty">今天還沒有記帳</div>';const recent=[...data.entries].sort(sortEntries).slice(0,5);$('#recentList').innerHTML=recent.length?recent.map(txHTML).join(''):'<div class="empty">新增第一筆紀錄開始使用</div>'}
function sortEntries(a,b){return `${b.date}T${b.time}`.localeCompare(`${a.date}T${a.time}`)}
function renderRecords(){let es=[...data.entries].sort(sortEntries);const t=$('#recordTypeFilter').value,q=$('#recordSearch').value.trim().toLowerCase();if(t!=='all')es=es.filter(e=>e.type===t);if(q)es=es.filter(e=>[e.note,e.category,accountName(e.accountId)].join(' ').toLowerCase().includes(q));$('#recordsList').innerHTML=es.length?es.map(txHTML).join(''):'<div class="empty">沒有符合的紀錄</div>'}
function renderAnalytics(){const es=currentMonthEntries();const expenses=es.filter(e=>e.type==='expense');const total=expenses.reduce((s,e)=>s+e.amount,0);$('#analyticsExpense').textContent=money(total);$('#dailyAvg').textContent=money(total/Math.max(1,new Date().getDate()));$('#largestExpense').textContent=money(Math.max(0,...expenses.map(e=>e.amount)));$('#txCount').textContent=es.length;const groups={};expenses.forEach(e=>groups[e.category]=(groups[e.category]||0)+e.amount);const rows=Object.entries(groups).sort((a,b)=>b[1]-a[1]);$('#categoryBreakdown').innerHTML=rows.length?rows.map(([k,v])=>`<div class="break-row"><div class="break-top"><span>${iconFor(k)} ${k}</span><strong>${money(v)}</strong></div><div class="break-track"><div style="width:${total?Math.max(4,v/total*100):0}%"></div></div></div>`).join(''):'<div class="empty">本月還沒有支出資料</div>';const days=[];for(let i=6;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);const key=d.toISOString().slice(0,10);const val=data.entries.filter(e=>e.date===key&&e.type==='expense').reduce((s,e)=>s+e.amount,0);days.push({label:`${d.getMonth()+1}/${d.getDate()}`,val})}const max=Math.max(1,...days.map(d=>d.val));$('#weekBars').innerHTML=days.map(d=>`<div class="bar-col"><div class="bar" style="height:${Math.max(3,d.val/max*120)}px" title="${money(d.val)}"></div><div class="bar-label">${d.label}</div></div>`).join('')}
function renderAccounts(){const sums={};data.accounts.forEach(a=>sums[a.id]=0);data.entries.forEach(e=>{if(!(e.accountId in sums))return;if(e.type==='income')sums[e.accountId]+=e.amount;if(e.type==='expense')sums[e.accountId]-=e.amount});$('#accountsList').innerHTML=data.accounts.map(a=>`<div class="account-item"><div class="account-left"><div class="account-icon">${a.type==='現金'?'💵':a.type==='信用卡'?'💳':a.type==='銀行'?'🏦':'👛'}</div><div class="account-meta"><strong>${escapeHtml(a.name)}</strong><small>${a.type}</small></div></div><strong>${money(sums[a.id])}</strong></div>`).join('')}
function renderSelects(){const cats=data.categories[entryType]||[];$('#categorySelect').innerHTML=cats.map(c=>`<option>${c}</option>`).join('');$('#accountSelect').innerHTML=data.accounts.map(a=>`<option value="${a.id}">${escapeHtml(a.name)}</option>`).join('')}
function renderAll(){renderHome();renderRecords();renderAnalytics();renderAccounts();renderSelects();$('#monthlyBudget').value=data.budget||''}
function openSheet(){renderSelects();const n=new Date();$('#dateInput').value=n.toISOString().slice(0,10);$('#timeInput').value=n.toTimeString().slice(0,5);$('#entrySheet').classList.add('open');$('#sheetBackdrop').classList.add('open');$('#entrySheet').setAttribute('aria-hidden','false');setTimeout(()=>$('#amountInput').focus(),250)}
function closeSheet(){$('#entrySheet').classList.remove('open');$('#sheetBackdrop').classList.remove('open');$('#entrySheet').setAttribute('aria-hidden','true')}
function resetEntry(){$('#amountInput').value='';$('#noteInput').value=''}
$$('[data-nav]').forEach(b=>b.addEventListener('click',()=>nav(b.dataset.nav)));['#fabAdd','#quickAddTop'].forEach(id=>$(id).addEventListener('click',openSheet));$('#sheetBackdrop').addEventListener('click',closeSheet);
$$('#typeSegment button').forEach(b=>b.addEventListener('click',()=>{entryType=b.dataset.type;$$('#typeSegment button').forEach(x=>x.classList.toggle('active',x===b));renderSelects()}));
$('#saveEntryBtn').addEventListener('click',()=>{const amount=Number($('#amountInput').value);if(!amount||amount<=0){alert('請輸入金額');return}data.entries.push({id:crypto.randomUUID(),type:entryType,amount,category:$('#categorySelect').value,accountId:$('#accountSelect').value,date:$('#dateInput').value,time:$('#timeInput').value,note:$('#noteInput').value.trim(),createdAt:Date.now()});saveData();resetEntry();closeSheet()});
$('#recordTypeFilter').addEventListener('change',renderRecords);$('#recordSearch').addEventListener('input',renderRecords);
$('#saveBudgetBtn').addEventListener('click',()=>{data.budget=Number($('#monthlyBudget').value)||0;saveData();alert('預算已儲存')});
$('#addAccountBtn').addEventListener('click',()=>$('#accountModal').classList.add('open'));$('#cancelAccount').addEventListener('click',()=>$('#accountModal').classList.remove('open'));$('#saveAccount').addEventListener('click',()=>{const name=$('#newAccountName').value.trim();if(!name)return;data.accounts.push({id:crypto.randomUUID(),name,type:$('#newAccountType').value});$('#newAccountName').value='';$('#accountModal').classList.remove('open');saveData()});
$('#exportBtn').addEventListener('click',()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`mymoney-backup-${todayKey()}.json`;a.click();URL.revokeObjectURL(a.href)});
$('#importInput').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;try{const parsed=JSON.parse(await f.text());if(!parsed.entries||!parsed.accounts)throw new Error();data={...defaultData,...parsed};saveData();alert('備份已匯入')}catch{alert('無法讀取這個備份檔')}});
$('#clearDataBtn').addEventListener('click',()=>{if(confirm('確定要清除全部記帳資料？此動作無法復原。')){data=structuredClone(defaultData);saveData()}});
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));
renderAll();
